version: "3.9"
services:
  postgres_1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Maltseva_BSE206"
      POSTGRES_USER: "Maltseva_BSE206"
      POSTGRES_PASSWORD: "Maltseva_BSE206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/scripts/db1:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
  postgres_2:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Maltseva_BSE206"
      POSTGRES_USER: "Maltseva_BSE206"
      POSTGRES_PASSWORD: "Maltseva_BSE206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/scripts/db2:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  postgres_3:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Maltseva_BSE206"
      POSTGRES_USER: "Maltseva_BSE206"
      POSTGRES_PASSWORD: "Maltseva_BSE206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/scripts/db3:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"